### ISSUE TITLE
Amazon S3 with S3 Object Lambda - Returns image thumbnail from S3 problem

### ISSUE THREAD

**Issue by lbrent2k** [aws-samples/serverless-patterns#698]
I run the CLI command below and it fails (see Lambda log below):

aws s3api get-object --bucket 'arn:aws:s3-object-lambda:us-east-1:9********970810:accesspoint/resize-olap' --key example1.jpg './images/example1-thumbnail.jpg'

***************************************

2022-05-25T22:42:47.884Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Error",
    "errorMessage": "'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.",
    "stack": [
        "Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.",
        "    at Object.hasVendoredLibvips (/var/task/node_modules/sharp/lib/libvips.js:82:13)",
        "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:7:22)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/node_modules/sharp/lib/index.js:3:15)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)"
    ]
}

**Comment by jbesw** [comment]
Contacting the author for follow-up.

**Comment by gadavis2** [comment]
You may be using a Mac to deploy this solution.  I personally use a Windows PC.  When using a Mac or Windows PC, you need to perform additional actions to ensure Lambda functions are built using Linux binaries.  Simply using `sam build` alone will use binaries that match the native operating system.

You have two options:
1. [Install Docker](https://docs.docker.com/desktop/), then use `sam build --use-container` which tells SAM to build inside a Lambda-like Docker container that uses Linux binaries.
2. Deploy the solution inside an AWS Cloud9 environment.

I just tested option 1 from a Windows PC and it worked great.

**Comment by lbrent2k** [comment]
I installed Docker.  Build worked.  Deploy yields following error:

DELETE_COMPLETE                       AWS::S3::AccessPoint                  S3AccessPoint                         Delete succeeded for the resources  
                                                                                                                  that failed to create.              
CREATE_IN_PROGRESS                    AWS::S3::AccessPoint                  S3AccessPoint                         -                                   
CREATE_FAILED                         AWS::S3::AccessPoint                  S3AccessPoint                         resize-ap already exists in stack   
                                                                                                                  arn:aws:cloudformation:us-          
                                                                                                                  east-1:962****970810:stack/object-   
                                                                                                                  resize-app/3cc4f710-dc6d-11ec-a632- 
                                                                                                                  0a0feb7e81f9                        
UPDATE_FAILED                         AWS::CloudFormation::Stack            thumber                               The following resource(s) failed to 
                                                                                                                  create: [S3AccessPoint].            
-----------------------------------------------------------------------------------------------------------------------------------------------------

Failed to deploy. Automatic rollback disabled for this deployment.

Actions you can take next
=========================
[*] Fix issues and try deploying again
[*] Roll back stack to the last known stable state: aws cloudformation rollback-stack --stack-name thumber

Error: Failed to create/update the stack: thumber, Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "UPDATE_FAILED" at least once

**Comment by gadavis2** [comment]
It looks like your previous stack did not delete completely before deploying again.  I would recommend going to CloudFormation and deleting the stack and try to deploy a new stack.
